#!/usr/bin/env python3

from fakewebcam import Server
from fakewebcam import FakeWebcam

if __name__ == "__main__":
  fake_webcam = FakeWebcam.start()
  server = Server.start(fake_webcam, port=8080)
  server.wait_for()
